// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/ai-training" | "/admin/catalogue/batches" | "/admin/catalogue/courses" | "/admin/catalogue/faculty" | "/admin/catalogue/portfolio" | "/admin/catalogue/projects" | "/admin/catalogue/services" | "/admin/conversations" | "/admin/conversations/[id]" | "/admin/crm/admissions" | "/admin/crm/admissions/[id]" | "/admin/crm/customers" | "/admin/crm/follow-ups" | "/admin/crm/leads" | "/admin/crm/leads/[id]" | "/admin/crm/students" | "/admin/events" | "/admin/integrations" | "/admin/knowledge" | "/admin/logs" | "/admin/media" | "/admin/meetings" | "/admin/messaging/broadcasts" | "/admin/messaging/templates" | "/admin/messaging/whatsapp" | "/admin/notifications" | "/admin/quotes" | "/admin/reports" | "/admin/roles" | "/admin/settings" | "/admin/support/tickets" | "/admin/users" | "/chat" | "/login"
type AppRouteHandlerRoutes = "/api/admin/[entity]/[id]" | "/api/admin/activities" | "/api/admissions" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/catalog" | "/api/chat" | "/api/health" | "/api/leads" | "/api/meetings" | "/api/search" | "/api/tickets" | "/api/whatsapp/webhook"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/webhook"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/ai-training": {}
  "/admin/catalogue/batches": {}
  "/admin/catalogue/courses": {}
  "/admin/catalogue/faculty": {}
  "/admin/catalogue/portfolio": {}
  "/admin/catalogue/projects": {}
  "/admin/catalogue/services": {}
  "/admin/conversations": {}
  "/admin/conversations/[id]": { "id": string; }
  "/admin/crm/admissions": {}
  "/admin/crm/admissions/[id]": { "id": string; }
  "/admin/crm/customers": {}
  "/admin/crm/follow-ups": {}
  "/admin/crm/leads": {}
  "/admin/crm/leads/[id]": { "id": string; }
  "/admin/crm/students": {}
  "/admin/events": {}
  "/admin/integrations": {}
  "/admin/knowledge": {}
  "/admin/logs": {}
  "/admin/media": {}
  "/admin/meetings": {}
  "/admin/messaging/broadcasts": {}
  "/admin/messaging/templates": {}
  "/admin/messaging/whatsapp": {}
  "/admin/notifications": {}
  "/admin/quotes": {}
  "/admin/reports": {}
  "/admin/roles": {}
  "/admin/settings": {}
  "/admin/support/tickets": {}
  "/admin/users": {}
  "/api/admin/[entity]/[id]": { "entity": string; "id": string; }
  "/api/admin/activities": {}
  "/api/admissions": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/catalog": {}
  "/api/chat": {}
  "/api/health": {}
  "/api/leads": {}
  "/api/meetings": {}
  "/api/search": {}
  "/api/tickets": {}
  "/api/whatsapp/webhook": {}
  "/chat": {}
  "/login": {}
  "/webhook": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
