// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(admin)/admin/ai-training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ai-training">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/ai-training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/batches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/batches">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/batches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/courses">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/faculty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/faculty">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/faculty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/portfolio">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/projects">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/catalogue/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/catalogue/services">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/catalogue/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/conversations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/conversations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/admissions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/admissions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/admissions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/admissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/admissions">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/admissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/follow-ups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/follow-ups">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/follow-ups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/leads/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/leads">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/crm/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/students">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/crm/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/events">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/logs">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/meetings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/meetings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/messaging/broadcasts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messaging/broadcasts">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/messaging/broadcasts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/messaging/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messaging/templates">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/messaging/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/messaging/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messaging/whatsapp">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/messaging/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/roles">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/support/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/support/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(chat)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../src/app/(chat)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/[entity]/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/[entity]/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/[entity]/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/activities">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../src/app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/meetings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings">> = Specific
  const handler = {} as typeof import("../../src/app/api/meetings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/whatsapp/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/whatsapp/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
