import { prisma } from "@/lib/db";
import { notifyTeam } from "@/lib/notify";
import { sendText } from "@/lib/whatsapp/client";

export interface DailyBakeryReportData {
  dateStr: string;
  totalOrders: number;
  deliveredOrders: number;
  totalRevenue: number;
  orders: Array<{
    reference: string;
    customerName: string;
    phone: string;
    amount: number;
    stage: string;
    requirements: string;
    createdAt: Date;
  }>;
}

export async function generateDailyBakeryReport(): Promise<DailyBakeryReportData> {
  // Calculate PKT (Asia/Karachi) Start of Day (00:00:00 PKT)
  const now = new Date();
  const pktDateStr = now.toLocaleDateString("en-CA", { timeZone: "Asia/Karachi" }); // "YYYY-MM-DD"
  const startOfPktDay = new Date(`${pktDateStr}T00:00:00+05:00`);

  // Query ALL orders placed across ANY customer phone number / web thread today in PKT
  const leads = await prisma.marketingLead.findMany({
    where: {
      createdAt: { gte: startOfPktDay },
    },
    orderBy: { createdAt: "asc" },
  });

  const totalOrders = leads.length;
  const deliveredOrders = leads.filter((l) => l.stage === "WON" || l.stage === "QUALIFIED").length;
  let totalRevenue = 0;

  const orders = leads.map((l) => {
    const val = Number(l.estimatedValue || 0);
    totalRevenue += val;
    return {
      reference: l.reference,
      customerName: l.name,
      phone: l.phone,
      amount: val,
      stage: l.stage,
      requirements: l.requirements,
      createdAt: l.createdAt,
    };
  });

  const displayDate = now.toLocaleDateString("en-PK", {
    timeZone: "Asia/Karachi",
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const reportData: DailyBakeryReportData = {
    dateStr: displayDate,
    totalOrders,
    deliveredOrders,
    totalRevenue,
    orders,
  };

  // Upsert daily analytics record in DB
  const analyticsDate = new Date(`${pktDateStr}T00:00:00.000Z`);
  await prisma.analyticsDaily.upsert({
    where: {
      date_department: {
        date: analyticsDate,
        department: "MARKETING",
      },
    },
    update: {
      leads: totalOrders,
      revenue: totalRevenue,
    },
    create: {
      date: analyticsDate,
      department: "MARKETING",
      leads: totalOrders,
      revenue: totalRevenue,
    },
  }).catch(() => {});

  return reportData;
}

export async function sendDailyBakeryReportToOwner(): Promise<{ success: boolean; reportText: string }> {
  const data = await generateDailyBakeryReport();

  let text = `📊 *CAKESTRY BAKERY — DAILY 11:00 PM PKT SUMMARY REPORT*\n`;
  text += `📅 *Date:* ${data.dateStr}\n\n`;
  text += `📦 *ALL Orders Received Today:* ${data.totalOrders}\n`;
  text += `✅ *Fulfilled / Qualified Orders:* ${data.deliveredOrders}\n`;
  text += `💰 *TOTAL DAILY SALES REVENUE: Rs. ${data.totalRevenue.toLocaleString()}*\n`;
  text += `=====================================\n\n`;

  text += `📋 *ALL ORDER DETAILS TODAY:*\n`;
  if (data.orders.length === 0) {
    text += `_No orders recorded today across any customer numbers._\n`;
  } else {
    data.orders.forEach((o, idx) => {
      text += `\n*Order #${idx + 1}: Ref ${o.reference}*\n`;
      text += `👤 *Customer Name:* ${o.customerName}\n`;
      text += `📞 *Phone:* ${o.phone}\n`;
      text += `💰 *Amount:* Rs. ${o.amount.toLocaleString()}\n`;
      text += `📌 *Status:* ${o.stage}\n`;
      if (o.requirements) {
        text += `📝 *Items & Details:*\n${o.requirements.replace(/^/gm, "   ")}\n`;
      }
      text += `-------------------------------------\n`;
    });
  }

  text += `\n✨ Automated Daily Report generated by Cakestry AI Assistant.`;

  // Send WhatsApp report to Bakery Owner (0329-3110006)
  const ownerWaId = "923293110006";
  await sendText(ownerWaId, text).catch((e) => console.warn("[report] WhatsApp report failed:", e));

  // Send Email report to Bakery Owner
  await notifyTeam({
    department: "MARKETING",
    subject: `📊 ALL ORDERS REPORT (${data.dateStr}) — Total: Rs. ${data.totalRevenue.toLocaleString()}`,
    body: text,
    link: "/admin/reports",
  }).catch((e) => console.warn("[report] Email report failed:", e));

  return { success: true, reportText: text };
}
